Missing dependencies from yarn
Hi, 

when trying to install a new Symfony demo app on Platform.sh, using: 
```
symfony new symfony-demo --demo --cloud
cd symfony-demo
symfony cloud:create
symfony deploy
```
i get this error during PSH deploy 

```
yarn run v1.22.19
          $ /app/node_modules/.bin/encore production
          W: node:internal/modules/cjs/loader:998
          W:   throw err;
          W:   ^
          W: Error: Cannot find module '@babel/core'
```

When running yarn install, some dependencies are missing so i needed to add them into package.json for deployment to success
```
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @symfony/stimulus-bridge@3.2.1" has unmet peer dependency "@hotwired/stimulus@^3.0".
warning "@symfony/stimulus-bridge > @hotwired/stimulus-webpack-helpers@1.0.1" has unmet peer dependency "@hotwired/stimulus@>= 3.0".
warning " > @symfony/webpack-encore@4.1.2" has unmet peer dependency "@babel/core@^7.17.0".
warning " > @symfony/webpack-encore@4.1.2" has unmet peer dependency "@babel/preset-env@^7.16.0".
warning " > @symfony/webpack-encore@4.1.2" has unmet peer dependency "webpack@^5.72".
warning " > @symfony/webpack-encore@4.1.2" has unmet peer dependency "webpack-cli@^4.9.1".
warning "@symfony/webpack-encore > @nuxt/friendly-errors-webpack-plugin@2.5.2" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@symfony/webpack-encore > assets-webpack-plugin@7.0.0" has unmet peer dependency "webpack@>=5.0.0".
warning "@symfony/webpack-encore > babel-loader@8.3.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@symfony/webpack-encore > babel-loader@8.3.0" has unmet peer dependency "webpack@>=2".
warning "@symfony/webpack-encore > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0".
warning "@symfony/webpack-encore > css-loader@6.7.3" has unmet peer dependency "webpack@^5.0.0".
warning "@symfony/webpack-encore > css-minimizer-webpack-plugin@4.2.2" has unmet peer dependency "webpack@^5.0.0".
warning "@symfony/webpack-encore > mini-css-extract-plugin@2.7.2" has unmet peer dependency "webpack@^5.0.0".
warning "@symfony/webpack-encore > style-loader@3.3.1" has unmet peer dependency "webpack@^5.0.0".
warning "@symfony/webpack-encore > terser-webpack-plugin@5.3.6" has unmet peer dependency "webpack@^5.1.0".
warning "@symfony/webpack-encore > webpack-dev-server@4.11.1" has unmet peer dependency "webpack@^4.37.0 || ^5.0.0".
warning "@symfony/webpack-encore > webpack-dev-server > webpack-dev-middleware@5.3.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eonasdan-bootstrap-datetimepicker@4.17.49" has unmet peer dependency "bootstrap@^3.3".
warning " > eonasdan-bootstrap-datetimepicker@4.17.49" has unmet peer dependency "moment@^2.10".
warning " > eonasdan-bootstrap-datetimepicker@4.17.49" has unmet peer dependency "moment-timezone@^0.4.0 || ^0.5.0".
warning " > sass-loader@12.6.0" has unmet peer dependency "webpack@^5.0.0".
```

And upgrading sass-loader to version 13 as well to avoid having this warning during PSH deploy: 
```
           WARNING  Webpack Encore requires version ^13.0.0 of sass-loader, but your version (12.6.0) is too old. The related feature will probably *not* work correctly.
```

hope it helps.